language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jashaikh/simple-react-app-with-docker -f Dockerfile.dev .

script:
  - docker run jashaikh/simple-react-app-with-docker npm run test -- --coverage