language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jashaikh/simple-react-app-with-docker -f Dockerfile.dev .

script:
  - docker run  -e CI=true jashaikh/simple-react-app-with-docker npm run test -- --coverage

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "simple-react-with-docker"
  env: "SimpleReactWithDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-298006206862"
  bucket_path: "simple-react-with-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY